Feat/frame
GazzolaLab/Blender-Soft-Rod pull request #25
Opened 2024-08-09 20:52 UTC by hanson-hschang

Add three things:

- add Frame class: able to set the end frame
- add set_view_distance method: zoom in or out
- change version to VERSION: and add type hint Final to show it is a constant

2024-08-11 16:01 UTC, skim0119 commented
> change version to VERSION

I don't see why this change is necessary.

Can you give an example of how to use these features in the documentation?

2024-08-11 18:34 UTC, hanson-hschang commented
All caps variable is used to define constant?
Or maybe “version” key word has its own style guide?

It can be used to check if the version is what you want.


BSR_AVALIBILITY = True
try:
    import bsr
    if bsr.VERSION <= “0.1.0”:
        raise ImportError
except ImportError:
    BSR_AVAILABLE = False

if BSR_AVALIBITY:
    bsr.clear_mesh_objects()

Something like this.


However, it doesn’t really matter to me wether it is all caps or not. Let’s
use one that is more commonly used. However, the Final type hint should be
added in there, I think.



Heng-Sheng Chang
Teaching Assistant & Graduate Research Assistant
Mechanical Science and Engineering & Coordinated Science Laboratory
University of Illinois at Urbana-Champaign


On Sun, Aug 11, 2024 at 11:02 AM Seung Hyun Kim ***@***.***>
wrote:

> change version to VERSION
>
> I don't see why this change is necessary.
>
> Can you give an example of how to use these features in the documentation?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/GazzolaLab/Blender-Soft-Rod/pull/25*issuecomment-2282805553__;Iw!!DZ3fjg!_lPlCPjeI4IL0DlA5NCYeX8bJhPU-V-X-1wV5jtKj4nDGmnzJejMtIjXzhq5A449uJdum4pCnQ2tZXHgtuOYREvRLLXc$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AJEQGOPAIRMHE3TNCSAXTADZQ6DH3AVCNFSM6AAAAABMJDZAW2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBSHAYDKNJVGM__;!!DZ3fjg!_lPlCPjeI4IL0DlA5NCYeX8bJhPU-V-X-1wV5jtKj4nDGmnzJejMtIjXzhq5A449uJdum4pCnQ2tZXHgtuOYRC3_6rDs$>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-12 15:46 UTC, skim0119 requested changes

2024-08-12 15:46 UTC, skim0119 commented on src/bsr/__init__.py
> +class Frame:
Need documentation. Also it can move to frame.py

2024-08-12 15:46 UTC, skim0119 commented on src/bsr/__init__.py
> +def find_area(area_type: str) -> Optional[bpy.types.Area]:
Lets add documentation, and move `find_area` and `set_view_distance` to `viewport.py`.

2024-08-12 20:21 UTC, skim0119 approved these changes
LGTM

2024-08-13 04:36 UTC, skim0119 commented
@hanson-hschang Thanks for fixing the issue

2024-08-13 04:48 UTC, hanson-hschang commented
@skim0119 Please review the code again~ I change the implementation of singleton from Mixin to metaclass. It is easier to implement the classes that requires singleton property. Don't have to do the following in the `__init__` method
```python
def __init__(self):
    if not self.isInstantiated:
        self.__frame: int = 0
```
Directly, one can use the following instead
```python
def __init__(self):
    self.__frame: int = 0
```

2024-08-13 04:50 UTC, skim0119 commented
@hanson-hschang Okay, I'll merge after some test

2024-08-14 08:18 UTC, skim0119 approved these changes

2024-08-14 08:18 UTC, merged